### ISSUE TITLE
Lidar collision detection isn't working properly

### ISSUE THREAD

**Issue by AHoehbusch** [NVIDIA-Omniverse/OmniIsaacGymEnvs#24]
Hi, we're trying to use this repository to train multiple robots that use Lidar sensors for detecting obstacles. For testing if the sensors work correctly, we added a cube (with the collision API enabled) to the default environment. When running the simulation with the random policy script however, the Lidars don't seem to detect any obstacles. This can be remedied by selecting the cube in the GUI and disabling and enabling the collision API of the cube again, but this workaround only works for objects in the default environment and not for any of the clones.

This is a screenshot of the scene after starting the simulation
![Bildschirmfoto von 2023-01-17 14-23-24](https://user-images.githubusercontent.com/49786641/212910358-0756d6f6-3d95-43ce-a4c8-7126a3e66968.png)

This is a screenshot of the scene after disabling and reenabling the collision api of the cube in env_0
![Bildschirmfoto von 2023-01-17 14-23-55](https://user-images.githubusercontent.com/49786641/212910390-a14aeeff-360b-44c1-8405-fce28654810a.png)

Is there any way to configure the scene so the Lidar sensors work properly in every environment without having to use the GUI?

**Comment by kellyguo11** [comment]
Hi there, could you try setting `enable_scene_query_support: True` in your task config file? Having this flag set to False will disable scene queries in order to improve performance.
