### ISSUE TITLE
PhysX error: The application needs to increase PxgDynamicsMemoryConfig::totalAggregatePairsCapacity

### ISSUE THREAD

**Issue by Toni-SM** [NVIDIA-Omniverse/OmniIsaacGymEnvs#3]
Hi

For the **Ant** environment, if the training process is not perfect (in which all ants advance and there is no overlap with other environments), several environments cross and generate the following error. 

```
2022-06-08 12:23:10 [191,143ms] [Error] [omni.physx.plugin] PhysX error: The application needs to increase PxgDynamicsMemoryConfig::totalAggregatePairsCapacity to 4120 , otherwise, the simulation will miss interactions
, FILE /buildAgent/work/99bede84aa0a52c2/source/gpubroadphase/src/PxgAABBManager.cpp, LINE 1064
```

The problem seems to be in the way of filtering collisions between clones. This error only occurs in environments where there is a possibility of intersection, but not with static environments such as Cartpole or Allegro/Shadow-Hand

By changing some training configuration (AntPPO.yaml file), it is possible to reproduce the error:

```yaml
normalize_input: False
normalize_value: False
schedule_type: standard
```

A possible solution is to increase the `gpu_total_aggregate_pairs_capacity` but the most simple one is to increase the space between the environments (`envSpacing`)

**Comment by kellyguo11** [comment]
When environments come across each other, it's likely they will generate additional contacts and collisions. We filter out collisions between environments by default so that these collisions will be ignored. Both of your solutions will work in this case.
