### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by ARobbins67** [NVIDIA-Omniverse/OmniIsaacGymEnvs#30]
Can't solve the following syntax error. Running on Windows 11 cmd. I set PYTHON_PATH in the python.bat environment but now it's not letting me run rlgames_train.py

```
>>> PYTHON_PATH scripts/rlgames_train.py task=Cartpole
  File "<stdin>", line 1
    PYTHON_PATH scripts/rlgames_train.py task=Cartpole
                      ^
SyntaxError: invalid syntax
```
Tried running this in and out of the python environment. Any help is greatly appreciated.

**Comment by ADebor** [comment]
Hi, it seems like you're trying to run the script from within the Python interpreter directly, which is not how it should be ran. See [this topic](https://stackoverflow.com/questions/13961140/syntax-error-when-using-command-line-in-python).

**Comment by kellyguo11** [comment]
Hi there, yes it appears from the error message that you are trying to run the command from within the Python interpreter. The command should be run directly from the command prompt (outside of the Python interpreter).
