### ISSUE TITLE
links coordination do not follow robot's movement

### ISSUE THREAD

**Issue by fanshi14** [NVIDIA-Omniverse/OmniIsaacGymEnvs#4]
Hi all,

I met one problem that the link's coordination keeps static when robot base is moving as the [video](https://drive.google.com/file/d/1Gb1JuwANiS9ZH7iR1ep1aUjGm3tf7PRe/view?usp=sharing).
`$ PYTHON_PATH scripts/random_policy.py task=Ant num_envs=1`
It causes a big problem when adding sensors to the link, for example the IMU sensor will always output lin_acc [0, 0, 9.8] and ang_vel [0, 0, 0] when adding to the torso.

Meanwhile I checked IMU example in Isaac Sim, and the coordinate worked perfectly as the [video](https://drive.google.com/file/d/1Ym_nLao-TvNfFhCSzMYC4YsaLFLdkeQv/view?usp=sharing).

Failed to find the reason after checking codes. I really appreciate it if you can give some hints.

**Comment by kellyguo11** [comment]
Hi @fanshi14 ,

We have disabled USD updates by default for the OmniIsaacGymEnvs examples to improve performance during training. If performance is not a major concern for you, you can try setting `use_flatcache: False` in the task config file, and run with the CPU pipeline `PYTHON_PATH scripts/random_policy.py task=Ant num_envs=1 pipeline=cpu`.

**Comment by berttggg** [comment]
Hello, I try the same thing in Orbit, but it seems it does not work. May I know what I should do? 
Thank you in advance!
