### ISSUE TITLE
Issue with training with GEAR JOINT (replicator)

### ISSUE THREAD

**Issue by arminvburren** [NVIDIA-Omniverse/OmniIsaacGymEnvs#53]
Hello,

I am training a robot whic has a lot of gear joints. I have 2 models, one with the gear joints and one without them (normal joints instead).

The training goes well with the model with normal joints, but it crashes at startup with gear joints with the following error:

```
2023-05-25 14:30:44 [14,043ms] [Warning] [omni.physx.plugin] PhysX warning: PxSerializationRegistry::getSerializer: failed to find PxSerializer instance for type 263, FILE /buildAgent/work/f25a4639a4b1bdc1/source/physxextensions/src/serialization/SnSerializationRegistry.cpp, LINE 205
/home/me/.local/share/ov/pkg/isaac_sim-2022.2.0/python.sh: line 41: 454867 Segmentation fault      (core dumped) $python_exe "$@" $args
There was an error running python
```

What I have found is that **it happens when there is more than one robot instanciated**. When I chose the number of env at 1, it works.

Do you have any idea of why this happen ? Something deep in the replicator code ?

Regards,

**Comment by kellyguo11** [comment]
Hi there, it's possible that gear joints are not currently supported by the physics replication feature in the cloner. You can try to disable this by setting `replicate_physics=False` in `set_up_scene`.
