### ISSUE TITLE
Installing Omniverse and OmniIsaacGymEnvs in WSL 2

### ISSUE THREAD

**Issue by sambaPython24** [NVIDIA-Omniverse/OmniIsaacGymEnvs#70]
Hey, I am trying to install Omniverse and OmniIsaacGymEnvs in WSL 2. 
In Windows 11, the Ubuntu GUIs open just like in Ubuntu. 

However, when trying to log in the Omniverse Launcher, I get the errors

```pyhton
16:04:07.653 › (node:326187) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, access '/home/user/.nvidia-omniverse/config/auth.toml'
```

```python
16:04:07.654 › (node:326187) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 23)
```
which appears to mean, that I do not have authorization toml file. 

And indeed, the ```/home/user/.nvidia-omniverse/config``` path only contains the Nucleas, the Navigator and omniverse.toml.
```
(base) user@DESKTOP-764:~/.nvidia-omniverse/config$ dir
Nucleus\ Navigator  omniverse.toml
```

Can I add the remaining by hand?

**Comment by gavrielstate** [comment]
I'm afraid that we don't support running Omniverse apps in WSL on Windows.

I would recommend using the Windows version of Isaac Sim instead.
