### ISSUE TITLE
anymal_instanceable.usd

### ISSUE THREAD

**Issue by SengHongLEE** [NVIDIA-Omniverse/OmniIsaacGymEnvs#97]
How can I get "../Isaac/Robots/ANYbotics/anymal_instanceable.usd" without accessing the localhost server?

**Comment by sujitvasanth** [comment]
you can navigate in the IsaacSim content browser to
omniverse://localhost/NVIDIA/Assets/Isaac/2023.1.0/Isaac/Robots/
or the 2022.2.1 equivilent

![Screenshot from 2023-11-04 19-00-04](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/assets/18464444/75ec8dfe-4d0b-4988-a57d-574031c2d22b)

right click and download.. I have included a zip of the files you wanted
[ANYbotics.zip](https://github.com/NVIDIA-Omniverse/OmniIsaacGymEnvs/files/13257503/ANYbotics.zip)

**Comment by SengHongLEE** [comment]
Thank lots for your responses on time. I have reached the file through localhost with your clear tutorial.
